"""Update Issue model with location fields

Revision ID: 7c49e80d7309
Revises: c84bad9eaef3
Create Date: 2025-09-19 19:01:32.955954

"""

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = "7c49e80d7309"
down_revision = "c84bad9eaef3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("issue", schema=None) as batch_op:
        batch_op.add_column(sa.Column("image_urls", sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column("video_note_url", sa.String(), nullable=True))
        batch_op.add_column(
            sa.Column("issue_type", sa.String(length=50), nullable=True)
        )
        batch_op.add_column(sa.Column("latitude", sa.Float(), nullable=False))
        batch_op.add_column(sa.Column("longitude", sa.Float(), nullable=False))
        batch_op.add_column(sa.Column("address", sa.String(length=200), nullable=True))
        batch_op.drop_index(batch_op.f("idx_issue_location"), postgresql_using="gist")
        batch_op.drop_column("location")
        batch_op.drop_column("photo_url")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("issue", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("photo_url", sa.VARCHAR(), autoincrement=False, nullable=True)
        )
        batch_op.add_column(
            sa.Column(
                "location",
                geoalchemy2.types.Geometry(
                    geometry_type="POINT",
                    srid=4326,
                    dimension=2,
                    from_text="ST_GeomFromEWKT",
                    name="geometry",
                    nullable=False,
                    _spatial_index_reflected=True,
                ),
                autoincrement=False,
                nullable=False,
            )
        )
        batch_op.create_index(
            batch_op.f("idx_issue_location"),
            ["location"],
            unique=False,
            postgresql_using="gist",
        )
        batch_op.drop_column("address")
        batch_op.drop_column("longitude")
        batch_op.drop_column("latitude")
        batch_op.drop_column("issue_type")
        batch_op.drop_column("video_note_url")
        batch_op.drop_column("image_urls")

    # ### end Alembic commands ###
